# Vocabulary files that were just created
src_vocab: ../hind_eng/hind_eng_vocab/run/hindi_english.vocab.src
tgt_vocab: ../hind_eng/hind_eng_vocab/run/hindi_english.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: hind_eng/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500

# corpus opts:
data:
  corpus_1:
    path_src: ../hind_eng/train/src-train.txt
    path_tgt: ../hind_eng/train/tgt-train.txt
  valid:
    path_src: ../hind_eng/val/src-val.txt
    path_tgt: ../hind_eng/val/tgt-val.txt
